spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

reminder:
  window-days: 3
  cron: "0 0 8 * * *"
  from-email: "u@gmail.com"

jwt:
  secret: ${JWT_SECRET}
  expiration: 1800000

server:
  address: 0.0.0.0
  port: 8080