spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# =========================
# KILL ALL HIBERNATE LOG
# =========================
logging:
  level:
    org.hibernate: OFF

# =========================
# REMINDER CONFIG
# =========================
reminder:
  window-days: ${REMINDER_WINDOW_DAYS:3}
  cron: ${REMINDER_CRON:0 0 8 * * *}
  from-email: ${REMINDER_FROM_EMAIL:no-reply@expiry.local}

# =========================
# JWT
# =========================
jwt:
  secret: ${JWT_SECRET}
  expiration: 1800000

# =========================
# OPENAI
# =========================
openai:
  api-key: ${OPENAI_API_KEY}
# =========================
# SERVER
# =========================
server:
  address: 0.0.0.0
  port: 8080